sstp_hub_name: SSTP
sstp_server_port: 443
sstp_users:
  john:
    password: 12345
  serg:
    password: pass4word!

vpn_domain_name: mydomain.com
regenerate_certificate: false

dhcp_settings:
  start: 10.100.30.10 
  end: 10.100.30.15 
  mask: 255.255.255.0 
  dns: none 
  dns2: none 
  domain: none 
  expire: 2000000 
  gateway: none
  log: no

vpn_settings:
 ip: 10.100.30.1
 mtu: 1412
 log: no
 udptimeout: 60
 tcptimeout: 1800
 mac: 5E-64-EB-E1-14-1F
 mask: 255.255.255.0
