- name: enable L2TP over IPsec
  become: true
  become_user: root
  command: >
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /ADMINHUB:default /CMD
    IPsecEnable /L2TP:yes /L2TPRAW:no /ETHERIP:no /PSK:mypass /DEFAULTHUB:default

- name: additional settings
  become: true
  become_user: root
  command: "{{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:default /CMD {{ item }}"
  loop:
    - SecureNatEnable
    - NatEnable
    - DHCPEnable
