##- name: enable L2TP over IPsec
##  become: true
##  become_user: root
##  command: >
##    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /ADMINHUB:default /CMD
##    IPsecEnable /L2TP:yes /L2TPRAW:no /ETHERIP:no /PSK:mypass /DEFAULTHUB:default

- name: dhcp settings
  become: true
  become_user: root
  command: > 
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:default /CMD
    DhcpSet /START:{{ dhcp_settings.start }} /END:{{ dhcp_settings.end }} /MASK:{{ dhcp_settings.mask }}
    /GW:{{ dhcp_settings.gateway }}
    /DNS:{{ dhcp_settings.dns }} /DNS2:{{ dhcp_settings.dns2 }} /DOMAIN:{{ dhcp_settings.domain }}
    /EXPIRE:{{ dhcp_settings.expire }}  /LOG:{{ dhcp_settings.log }}
  when: dhcp_settings is defined

- name: additional settings
  become: true
  become_user: root
  command: "{{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:default /CMD {{ item }}"
  loop:
    - SecureNatEnable
    - NatEnable
    - DHCPEnable

- name: flush settings
  become: true
  become_user: root
  command: "{{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /CMD Flush"

