- name: Create Hub for SSTP
  become: true
  become_user: root
  command: >
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /CMD HubCreate {{ sstp_hub_name }} /PASSWORD
  ignore_errors: true

- name: Print sstp users
  ansible.builtin.debug:
    msg: SSTP user {{ item }}
    verbosity: 2
  with_dict: "{{ sstp_users }}"

- name: Create Users
  become: true
  become_user: root
  with_dict: "{{ sstp_users }}"
  shell: |-
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:{{ sstp_hub_name }} /CMD UserCreate {{ item.key }} /GROUP:none /REALNAME:none /NOTE:none;
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /HUB:{{ sstp_hub_name }} /CMD UserPasswordSet {{ item.key }} /PASSWORD:{{ item.value.password }}

- name: Generate certificate
  become: true
  become_user: root
  command: >
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /CMD ServerCertRegenerate {{ vpn_domain_name }}

- name: Export certificate
  become: true
  become_user: root
  args:
    chdir: "{{ vpnserver_dir }}"
  command: >
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /CMD ServerCertGet {{ vpn_domain_name }}.cer

- name: Get certificate content
  command: cat {{ vpnserver_dir }}/{{ vpn_domain_name }}.cer
  register: cert_content

- name: Print certificate
  ansible.builtin.debug:
    msg: SSTP certificate {{ cert_content }}
    verbosity: 2

- name: Configure SSTP options
  become: true
  become_user: root
  loop:
    - SstpEnable yes
  command: >
    {{ vpnserver_dir }}/vpncmd /SERVER 127.0.0.1 /CMD {{ item }}

- name: Get SSTP status
  become: true
  become_user: root
  loop:
    - StatusGet
  command: >
    {{ vpnserver_dir }}/vpncmd  /HUB:{{ sstp_hub_name }} /SERVER 127.0.0.1 /CMD {{ item }}
